exports.JWT_TOKEN = process.env.JWT_TOKEN || "DEVELOPMENT FUTURE PAY JWT TOKEN"

exports.JWT_REFRESH_TOKEN = process.env.JWT_REFRESH_TOKEN || "FUTUREPAY_REFRESH_TOKEN_FOR_DEVELOPMENT_PURPOSE"


exports.FLWAVE_SECRET = 'FLWSECK_TEST-a9fbc30903f7f159c18d711fec41a2fb-X'